//
// Generated file, do not edit! Created by opp_msgtool 6.3 from Global/Base/_30_Network/packetprocessing/DelayPacketTag.msg.
//

#ifndef __PACKETPROCESSING_DELAYPACKETTAG_M_H
#define __PACKETPROCESSING_DELAYPACKETTAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace packetprocessing {

class DelayPacketTag;

}  // namespace packetprocessing

#include "inet/common/TagBase_m.h" // import inet.common.TagBase


namespace packetprocessing {

/**
 * Class generated from <tt>Global/Base/_30_Network/packetprocessing/DelayPacketTag.msg:20</tt> by opp_msgtool.
 * <pre>
 * class DelayPacketTag extends inet::TagBase
 * {
 *     simtime_t delay;
 * }
 * </pre>
 */
class DelayPacketTag : public ::inet::TagBase
{
  protected:
    ::omnetpp::simtime_t delay = SIMTIME_ZERO;

  private:
    void copy(const DelayPacketTag& other);

  protected:
    bool operator==(const DelayPacketTag&) = delete;

  public:
    DelayPacketTag();
    DelayPacketTag(const DelayPacketTag& other);
    virtual ~DelayPacketTag();
    DelayPacketTag& operator=(const DelayPacketTag& other);
    virtual DelayPacketTag *dup() const override {return new DelayPacketTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual ::omnetpp::simtime_t getDelay() const;
    virtual void setDelay(::omnetpp::simtime_t delay);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DelayPacketTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DelayPacketTag& obj) {obj.parsimUnpack(b);}


}  // namespace packetprocessing


namespace omnetpp {

template<> inline packetprocessing::DelayPacketTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<packetprocessing::DelayPacketTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PACKETPROCESSING_DELAYPACKETTAG_M_H

