[General]
network = Florasat.Test_Individual.Florasat_Individual_Sats

rng-class = "cMersenneTwister"
*.**.result-recording-modes = -       # --> none
**.result-recording-modes = -         # --> none
**.statistic-recording = true #false
**.scalar-recording = true #false
**.vector-recording = true #false
**.vector-record-eventnumbers = true #false


repeat 				= 10 #2
#seed-0-mt 			= 23542 #${23542, 84242 ! repetition}
seed-0-mt = ${23542, 84242, 15937, 42781, 63029, 88143, 27456, 51904, 76328, 92115 ! repetition}
sim-time-limit 		= 1199s #50s # 
simtime-resolution 	= -11

# Initial parameters, they are overwritten running throug sh file
**.stats_altitude = 600 
**.stats_raan = 210

#####################
# Medium 
#####################
*.radioMedium.backgroundNoise.power 					= -110dBm # Original value -96.616dBm
*.radioMedium.mediumLimitCache.centerFrequency 			= 868MHz #Original Value Nan
*.radioMedium.mediumLimitCache.maxTransmissionDuration 	= 4s #original value 0.01s
*.radioMedium.mediumLimitCache.minInterferenceTime 		= 0s

#####################
# Satellites
#####################
**.numSatellites = 1

*.satellite[*].mobilityType 	= "Sat_Mob_SatelliteMobility_Standalone"
*.satellite[*].noradModuleType 	= "Sat_Mob_NoradA"


**.satellite[*].**.initFromDisplayString = false
*.satellite[*].mobility.faceForward 	 = true#false
*.satellite[*].mobility.updateInterval 	 = 20s # disable self-message update mechanism

*.satellite[*].NoradModule.satName  = "FLoRaSat"
*.satellite[*].NoradModule.satIndex = -1
*.satellite[*].NoradModule.baseYear = 20
*.satellite[*].NoradModule.baseDay  = 1.5


*.satellite[*].NoradModule.planes 		= 1
*.satellite[*].NoradModule.satPerPlane  = 1
*.satellite[*].NoradModule.eccentricity = 0.000001
*.satellite[*].NoradModule.inclination 	= 98
*.satellite[*].NoradModule.altitude 	= 600

# Single pass satellite
# Uncomment these line to execute with several raan. This is executed by sh file.
#*.satellite[0].NoradModule.raan 		= ${210, 200, 190, 180, 170}
*.satellite[0].NoradModule.raan = 170
*.satellite[0].NoradModule.meanAnomaly  = 373 
#*.satellite[0].*.satIndex = 0

#### Detecta Doppler
*.satellite[*].phyDSL.radio.receiver.enableCollisionOverlap = true
*.satellite[*].phyDSL.radio.receiver.minCollisionOverlap = 0s

# Set antenna mobility modules for satellite radios
*.satellite[*].phyDSL.radio.antenna.typename 		= "ConstantGainAntenna"
*.satellite[*].phyDSL.radio.antenna.mobilityModule  = "^.^.^.mobility"
*.satellite[*].phyISL.radio.antenna.mobilityModule  = "^.^.^.mobility"
*.satellite[*].phyGSL.radio.antenna.mobilityModule  = "^.^.^.mobility"

# Set antenna gain for radio 
*.satellite[*].phyDSL.radio.antenna.gain = 12dB

*.satellite[*].net.routingType = "Null_Routing" #"Base_Routing"
*.terminal[*].net.routingType  = "Ter_Null_Routing" #"Base_Routing"

*.**.numGroundLinks 					  = 40
*.satellite[*].**.interfaceTableModule    = ""

# LoRa PHY Configuration
**.radioMedium.typename 			= "LoRaMedium"
**.radioMedium.analogModel.typename = "LoRaAnalogModel"
							   
# Disable ISLs
**.intraPlaneIslDisabled = false
**.interPlaneIslDisabled = false

###########################
# LoRa Nodes (devices on ground)
###########################
**.numTerminals = 60 #30
*.terminal[*].phy.radio.antenna.mobilityModule 	= "^.^.^.mob"
*.terminal[*].dlk.mac.interfaceTableModule 		= ""
*.terminal[*].dlk.energySourceModule 			= ""

# Toda la informacion de LoraPhyPreamble se jala desde MacFrame
# El lora TP esta en dBm aunque no tiene unidad
*.terminal[*].dlk.mac.LoRaTP = intuniform(12, 14) #* 1dBm  #14
*.terminal[*].dlk.mac.LoRaSF = intuniform(10, 12) #11


#*.terminal[*].app.mlBox.modelPath = "/home/ylnner/Documents/omnet++/omnetpp-6.3.0/projects/florasat_v4_ult_routing/src/model_scripted.pt"
*.transmissionPredictor.modelPath = "/home/ylnner/Documents/omnet++/omnetpp-6.3.0/projects/florasat_v4_ult_routing/src/model_scripted.pt"
# --------- Finland ----------
#*.terminal[0].mob.radius = 0.0
#*.terminal[0].mob.centerLatitude = 60.169
#*.terminal[0].mob.centerLongitude = 24.938   # Helsinki

# --------- Estonia ----------
#*.terminal[1].mob.radius = 0.0
#*.terminal[1].mob.centerLatitude = 59.437
#*.terminal[1].mob.centerLongitude = 24.753   # Tallinn

# --------- Latvia ----------
#*.terminal[2].mob.radius = 0.0
#*.terminal[2].mob.centerLatitude = 56.949
#*.terminal[2].mob.centerLongitude = 24.105   # Riga


#*.terminal[*].app.initialLoRaCF = 868MHz 
#*.terminal[*].app.initialLoRaBW = 125 kHz
#*.terminal[*].app.initialLoRaCR = 4
#*.terminal[*].app.initialLoRaTP = 14dBm #14dBm
#*.terminal[*].app.initialLoRaSF = 11#12


####*.terminal[*].phy.radio.transmitter.centerFrequency = 868MHz
####*.terminal[*].phy.radio.transmitter.power 			= 8dBm
####*.terminal[*].phy.radio.transmitter.bandwidth 		= 125kHz


# Application
**.numberOfPacketsToSend = 0  	#${numberOfPAckets = 200..5000 step 200}  # 0 means infinite number of packets
**.timeToFirstPacket 	 = 1s   #time to first packet can be set at any moment
**.timeToNextPacket 	 = 50s	#time to next packet must follow the 1% duty cycle, you can find the limit time on SimpleLoRaApp

include devices/WorldWide-30.ini



###########################
# Stations
###########################
**.numStations = 3
include stations/WorldWide-20.ini


#####################
# Visualizer
#####################
# Disable medium visualizer completely
*.visualizer.canvasVisualizer.mediumVisualizer.typename = ""

*.visualizer.*.radioVisualizer.displayAntennaLobes = true
*.visualizer.*.dataLinkVisualizer.displayLinks = true
*.visualizer.*.mobilityVisualizer.displayMovementTrails = true
*.visualizer.*.mobilityVisualizer.movementTrailLineWidth = 1
*.visualizer.*.mobilityVisualizer.trailLength = 3000


#####################
# Routing
####################
##*.topologyControl.timeSliceLength 	= 5000ms


####################
# Mac parameters
#--------------- Transmit windows ---------------   
#**.ttwDuration = 180s                           # Duration of the transmission window
#**.ttwIdle = 0s                               	# Idle time between transmission windows
# **.Ntw =  ${Ntw = 1..15} 		    			# Number of transmission windows
#**.Ntw = 10										# Number of transmission windows
#--------------- UL transmit ---------------
#**.ttxStart_min = 2s                            # Minimum time to start first transmission
#**.ttxStart_max = 2s                            # Maximum time to start first transmission
#**.Ntx = 6										# Number of uplink transmissions


#**.enableSatDetect = true
##**.ttxStart_max = 120s
##**.ttxIdle_min = 30s                            # Minimum idle time between transmissions
##**.ttxIdle_max = 35s                           	# Maximum idle time between transmissions
##**.Ntw = 5										# Number of transmission windows
##**.Ntx = 6										# Number of transmission windows
##**.ttwDuration = 235s                           # Duration of the transmission window


**.ttxStart_max = 120s
##**.ttxIdle_min = 40s                            # Minimum idle time between transmissions
##**.ttxIdle_max = 60s                           	# Maximum idle time between transmissions
##**.Ntw = 2										# Number of transmission windows
##**.Ntx = 15										# Number of transmission windows
##**.ttwDuration = 1100s                           # Duration of the transmission window

# ttwDuration = approx (sim_duration / Ntw) = approx(1200/4) = approx(300)
