//
// Generated file, do not edit! Created by opp_msgtool 6.3 from Global/Messages/_30_Network/DDRARoutingHeader.msg.
//

#ifndef __ROUTING__DDRA_DDRAROUTINGHEADER_M_H
#define __ROUTING__DDRA_DDRAROUTINGHEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace routing {
namespace ddra {

class DDRARoutingHeader;

}  // namespace ddra
}  // namespace routing

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

// cplusplus {{
using namespace inet;
// }}


namespace routing {
namespace ddra {

/**
 * Enum generated from <tt>Global/Messages/_30_Network/DDRARoutingHeader.msg:11</tt> by opp_msgtool.
 * <pre>
 * enum PacketType
 * {
 *     NORMAL = 0;
 *     CONGESTED = 1;
 *     UNCONGESTED = 2;
 *     FAILURE = 3;
 * }
 * </pre>
 */
enum PacketType {
    NORMAL = 0,
    CONGESTED = 1,
    UNCONGESTED = 2,
    FAILURE = 3
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PacketType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PacketType& e) { int n; b->unpack(n); e = static_cast<PacketType>(n); }

/**
 * Class generated from <tt>Global/Messages/_30_Network/DDRARoutingHeader.msg:18</tt> by opp_msgtool.
 * <pre>
 * class DDRARoutingHeader extends inet::FieldsChunk
 * {
 *     PacketType type;
 *     int srcSat = -1;
 *     int dstSat = 1;
 *     int srcGs = -1;
 *     int dstGs = -1;
 *     int failureTarget = -1;
 * }
 * </pre>
 */
class DDRARoutingHeader : public ::inet::FieldsChunk
{
  protected:
    PacketType type = static_cast<routing::ddra::PacketType>(-1);
    int srcSat = -1;
    int dstSat = 1;
    int srcGs = -1;
    int dstGs = -1;
    int failureTarget = -1;

  private:
    void copy(const DDRARoutingHeader& other);

  protected:
    bool operator==(const DDRARoutingHeader&) = delete;

  public:
    DDRARoutingHeader();
    DDRARoutingHeader(const DDRARoutingHeader& other);
    virtual ~DDRARoutingHeader();
    DDRARoutingHeader& operator=(const DDRARoutingHeader& other);
    virtual DDRARoutingHeader *dup() const override {return new DDRARoutingHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual PacketType getType() const;
    virtual void setType(PacketType type);

    virtual int getSrcSat() const;
    virtual void setSrcSat(int srcSat);

    virtual int getDstSat() const;
    virtual void setDstSat(int dstSat);

    virtual int getSrcGs() const;
    virtual void setSrcGs(int srcGs);

    virtual int getDstGs() const;
    virtual void setDstGs(int dstGs);

    virtual int getFailureTarget() const;
    virtual void setFailureTarget(int failureTarget);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DDRARoutingHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DDRARoutingHeader& obj) {obj.parsimUnpack(b);}


}  // namespace ddra
}  // namespace routing


namespace omnetpp {

template<> inline routing::ddra::DDRARoutingHeader *fromAnyPtr(any_ptr ptr) { return check_and_cast<routing::ddra::DDRARoutingHeader*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __ROUTING__DDRA_DDRAROUTINGHEADER_M_H

