//
// Generated file, do not edit! Created by opp_msgtool 6.3 from Global/Messages/_30_Network/Net_QueueInsertionTimeTag.msg.
//

#ifndef __SATELLITE_NET_QUEUEINSERTIONTIMETAG_M_H
#define __SATELLITE_NET_QUEUEINSERTIONTIMETAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace satellite {

class Sat_Net_QueueInsertionTimeTag;

}  // namespace satellite

#include "inet/common/TagBase_m.h" // import inet.common.TagBase


namespace satellite {

/**
 * Class generated from <tt>Global/Messages/_30_Network/Net_QueueInsertionTimeTag.msg:6</tt> by opp_msgtool.
 * <pre>
 * class Sat_Net_QueueInsertionTimeTag extends inet::TagBase
 * {
 *     simtime_t insertionTime = inet::simTime();
 * }
 * </pre>
 */
class Sat_Net_QueueInsertionTimeTag : public ::inet::TagBase
{
  protected:
    ::omnetpp::simtime_t insertionTime = inet::simTime();

  private:
    void copy(const Sat_Net_QueueInsertionTimeTag& other);

  protected:
    bool operator==(const Sat_Net_QueueInsertionTimeTag&) = delete;

  public:
    Sat_Net_QueueInsertionTimeTag();
    Sat_Net_QueueInsertionTimeTag(const Sat_Net_QueueInsertionTimeTag& other);
    virtual ~Sat_Net_QueueInsertionTimeTag();
    Sat_Net_QueueInsertionTimeTag& operator=(const Sat_Net_QueueInsertionTimeTag& other);
    virtual Sat_Net_QueueInsertionTimeTag *dup() const override {return new Sat_Net_QueueInsertionTimeTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual ::omnetpp::simtime_t getInsertionTime() const;
    virtual void setInsertionTime(::omnetpp::simtime_t insertionTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Sat_Net_QueueInsertionTimeTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Sat_Net_QueueInsertionTimeTag& obj) {obj.parsimUnpack(b);}


}  // namespace satellite


namespace omnetpp {

template<> inline satellite::Sat_Net_QueueInsertionTimeTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<satellite::Sat_Net_QueueInsertionTimeTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SATELLITE_NET_QUEUEINSERTIONTIMETAG_M_H

