//
// Generated file, do not edit! Created by opp_msgtool 6.3 from Global/Messages/_30_Network/Net_DropPacketTag.msg.
//

#ifndef __SATELLITE_NET_DROPPACKETTAG_M_H
#define __SATELLITE_NET_DROPPACKETTAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace satellite {

class Sat_Net_DropPacketTag;

}  // namespace satellite

#include "inet/common/TagBase_m.h" // import inet.common.TagBase

#include "inet/common/Simsignals_m.h" // import inet.common.Simsignals


namespace satellite {

/**
 * Class generated from <tt>Global/Messages/_30_Network/Net_DropPacketTag.msg:9</tt> by opp_msgtool.
 * <pre>
 * class Sat_Net_DropPacketTag extends inet::TagBase
 * {
 *     bool silent = false;
 *     inet::PacketDropReason reason;
 * }
 * </pre>
 */
class Sat_Net_DropPacketTag : public ::inet::TagBase
{
  protected:
    bool silent = false;
    ::inet::PacketDropReason reason = static_cast<inet::PacketDropReason>(-1);

  private:
    void copy(const Sat_Net_DropPacketTag& other);

  protected:
    bool operator==(const Sat_Net_DropPacketTag&) = delete;

  public:
    Sat_Net_DropPacketTag();
    Sat_Net_DropPacketTag(const Sat_Net_DropPacketTag& other);
    virtual ~Sat_Net_DropPacketTag();
    Sat_Net_DropPacketTag& operator=(const Sat_Net_DropPacketTag& other);
    virtual Sat_Net_DropPacketTag *dup() const override {return new Sat_Net_DropPacketTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool getSilent() const;
    virtual void setSilent(bool silent);

    virtual ::inet::PacketDropReason getReason() const;
    virtual void setReason(::inet::PacketDropReason reason);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Sat_Net_DropPacketTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Sat_Net_DropPacketTag& obj) {obj.parsimUnpack(b);}


}  // namespace satellite


namespace omnetpp {

template<> inline satellite::Sat_Net_DropPacketTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<satellite::Sat_Net_DropPacketTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SATELLITE_NET_DROPPACKETTAG_M_H

