//
// Generated file, do not edit! Created by opp_msgtool 6.3 from Global/Messages/_30_Network/Net_ProcessPacketTag.msg.
//

#ifndef __SATELLITE_NET_PROCESSPACKETTAG_M_H
#define __SATELLITE_NET_PROCESSPACKETTAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace satellite {

class Net_ProcessPacketTag;

}  // namespace satellite

#include "inet/common/TagBase_m.h" // import inet.common.TagBase


namespace satellite {

/**
 * Class generated from <tt>Global/Messages/_30_Network/Net_ProcessPacketTag.msg:6</tt> by opp_msgtool.
 * <pre>
 * class Net_ProcessPacketTag extends inet::TagBase
 * {
 *     int64_t time;
 * }
 * </pre>
 */
class Net_ProcessPacketTag : public ::inet::TagBase
{
  protected:
    int64_t time = 0;

  private:
    void copy(const Net_ProcessPacketTag& other);

  protected:
    bool operator==(const Net_ProcessPacketTag&) = delete;

  public:
    Net_ProcessPacketTag();
    Net_ProcessPacketTag(const Net_ProcessPacketTag& other);
    virtual ~Net_ProcessPacketTag();
    Net_ProcessPacketTag& operator=(const Net_ProcessPacketTag& other);
    virtual Net_ProcessPacketTag *dup() const override {return new Net_ProcessPacketTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int64_t getTime() const;
    virtual void setTime(int64_t time);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Net_ProcessPacketTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Net_ProcessPacketTag& obj) {obj.parsimUnpack(b);}


}  // namespace satellite


namespace omnetpp {

template<> inline satellite::Net_ProcessPacketTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<satellite::Net_ProcessPacketTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SATELLITE_NET_PROCESSPACKETTAG_M_H

