//
// Generated file, do not edit! Created by opp_msgtool 6.3 from Global/Messages/_30_Network/Net_CstRoutingTag.msg.
//

#ifndef __ROUTING_NET_CSTROUTINGTAG_M_H
#define __ROUTING_NET_CSTROUTINGTAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace routing {

struct Hop;
class CstRoutingTag;

}  // namespace routing

#include "inet/common/TagBase_m.h" // import inet.common.TagBase


namespace routing {

/**
 * Enum generated from <tt>Global/Messages/_30_Network/Net_CstRoutingTag.msg:5</tt> by opp_msgtool.
 * <pre>
 * enum CstPacketType
 * {
 *     NORMAL = 0;
 *     CONTROL = 1;
 * }
 * </pre>
 */
enum CstPacketType {
    NORMAL = 0,
    CONTROL = 1
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CstPacketType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CstPacketType& e) { int n; b->unpack(n); e = static_cast<CstPacketType>(n); }

/**
 * Enum generated from <tt>Global/Messages/_30_Network/Net_CstRoutingTag.msg:10</tt> by opp_msgtool.
 * <pre>
 * enum HopType
 * {
 *     GS = 0;
 *     SAT = 1;
 *     DEV = 2;
 * }
 * </pre>
 */
enum HopType {
    GS = 0,
    SAT = 1,
    DEV = 2
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HopType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HopType& e) { int n; b->unpack(n); e = static_cast<HopType>(n); }

/**
 * Struct generated from Global/Messages/_30_Network/Net_CstRoutingTag.msg:17 by opp_msgtool.
 */
struct Hop
{
    Hop();
    HopType type = static_cast<routing::HopType>(-1);
    int id = 0;
    double lat = 0;
    double lon = 0;
    uint16_t alt = 0;
};

// helpers for local use
void __doPacking(omnetpp::cCommBuffer *b, const Hop& a);
void __doUnpacking(omnetpp::cCommBuffer *b, Hop& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Hop& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Hop& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>Global/Messages/_30_Network/Net_CstRoutingTag.msg:25</tt> by opp_msgtool.
 * <pre>
 * class CstRoutingTag extends inet::TagBase
 * {
 *     CstPacketType type;
 *     int srcGs = -1;
 *     int dstGs = -1;
 *     int srcId = -1;
 *     int dstId = -1;
 *     int srcSat = -1;
 *     int dstSat = -1;
 *     int hops = 0;
 *     int maxHops = -1;
 *     int isLoraNode = 0;
 *     int srcGsOrDev = 0;
 *     int dstGsOrDev = 0;
 *     bool roundTrip = false;
 *     Hop route[];
 * }
 * </pre>
 */
class CstRoutingTag : public ::inet::TagBase
{
  protected:
    CstPacketType type = static_cast<routing::CstPacketType>(-1);
    int srcGs = -1;
    int dstGs = -1;
    int srcId = -1;
    int dstId = -1;
    int srcSat = -1;
    int dstSat = -1;
    int hops = 0;
    int maxHops = -1;
    int isLoraNode = 0;
    int srcGsOrDev = 0;
    int dstGsOrDev = 0;
    bool roundTrip = false;
    Hop *route = nullptr;
    size_t route_arraysize = 0;

  private:
    void copy(const CstRoutingTag& other);

  protected:
    bool operator==(const CstRoutingTag&) = delete;

  public:
    CstRoutingTag();
    CstRoutingTag(const CstRoutingTag& other);
    virtual ~CstRoutingTag();
    CstRoutingTag& operator=(const CstRoutingTag& other);
    virtual CstRoutingTag *dup() const override {return new CstRoutingTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual CstPacketType getType() const;
    virtual void setType(CstPacketType type);

    virtual int getSrcGs() const;
    virtual void setSrcGs(int srcGs);

    virtual int getDstGs() const;
    virtual void setDstGs(int dstGs);

    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);

    virtual int getDstId() const;
    virtual void setDstId(int dstId);

    virtual int getSrcSat() const;
    virtual void setSrcSat(int srcSat);

    virtual int getDstSat() const;
    virtual void setDstSat(int dstSat);

    virtual int getHops() const;
    virtual void setHops(int hops);

    virtual int getMaxHops() const;
    virtual void setMaxHops(int maxHops);

    virtual int getIsLoraNode() const;
    virtual void setIsLoraNode(int isLoraNode);

    virtual int getSrcGsOrDev() const;
    virtual void setSrcGsOrDev(int srcGsOrDev);

    virtual int getDstGsOrDev() const;
    virtual void setDstGsOrDev(int dstGsOrDev);

    virtual bool getRoundTrip() const;
    virtual void setRoundTrip(bool roundTrip);

    virtual void setRouteArraySize(size_t size);
    virtual size_t getRouteArraySize() const;
    virtual const Hop& getRoute(size_t k) const;
    virtual Hop& getRouteForUpdate(size_t k) { return const_cast<Hop&>(const_cast<CstRoutingTag*>(this)->getRoute(k));}
    virtual void setRoute(size_t k, const Hop& route);
    virtual void insertRoute(size_t k, const Hop& route);
    [[deprecated]] void insertRoute(const Hop& route) {appendRoute(route);}
    virtual void appendRoute(const Hop& route);
    virtual void eraseRoute(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CstRoutingTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CstRoutingTag& obj) {obj.parsimUnpack(b);}


}  // namespace routing


namespace omnetpp {

inline any_ptr toAnyPtr(const routing::Hop *p) {return any_ptr(p);}
template<> inline routing::Hop *fromAnyPtr(any_ptr ptr) { return ptr.get<routing::Hop>(); }
template<> inline routing::CstRoutingTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<routing::CstRoutingTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __ROUTING_NET_CSTROUTINGTAG_M_H

