//
// Generated file, do not edit! Created by opp_msgtool 6.3 from Global/Messages/_30_Network/Net_StoreAndForward.msg.
//

#ifndef __ROUTING_NET_STOREANDFORWARD_M_H
#define __ROUTING_NET_STOREANDFORWARD_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace routing {

class Net_StoreAndForward;

}  // namespace routing

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace routing {

/**
 * Class generated from <tt>Global/Messages/_30_Network/Net_StoreAndForward.msg:7</tt> by opp_msgtool.
 * <pre>
 * class Net_StoreAndForward extends inet::FieldsChunk
 * {
 *     int dstNode;
 * }
 * </pre>
 */
class Net_StoreAndForward : public ::inet::FieldsChunk
{
  protected:
    int dstNode = 0;

  private:
    void copy(const Net_StoreAndForward& other);

  protected:
    bool operator==(const Net_StoreAndForward&) = delete;

  public:
    Net_StoreAndForward();
    Net_StoreAndForward(const Net_StoreAndForward& other);
    virtual ~Net_StoreAndForward();
    Net_StoreAndForward& operator=(const Net_StoreAndForward& other);
    virtual Net_StoreAndForward *dup() const override {return new Net_StoreAndForward(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDstNode() const;
    virtual void setDstNode(int dstNode);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Net_StoreAndForward& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Net_StoreAndForward& obj) {obj.parsimUnpack(b);}


}  // namespace routing


namespace omnetpp {

template<> inline routing::Net_StoreAndForward *fromAnyPtr(any_ptr ptr) { return check_and_cast<routing::Net_StoreAndForward*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __ROUTING_NET_STOREANDFORWARD_M_H

