//
// Generated file, do not edit! Created by opp_msgtool 6.3 from Global/Messages/_30_Network/SendOnTag.msg.
//

#ifndef __ROUTING_SENDONTAG_M_H
#define __ROUTING_SENDONTAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace routing {

class SendOnTag;

}  // namespace routing

#include "inet/common/TagBase_m.h" // import inet.common.TagBase

#include "Global/Utilities/ISLDirection_m.h" // import Global.Utilities.ISLDirection


namespace routing {

/**
 * Class generated from <tt>Global/Messages/_30_Network/SendOnTag.msg:24</tt> by opp_msgtool.
 * <pre>
 * class SendOnTag extends inet::TagBase
 * {
 *     core::isldirection::ISLDirection dir;
 * }
 * </pre>
 */
class SendOnTag : public ::inet::TagBase
{
  protected:
    ::core::isldirection::ISLDirection dir = static_cast<core::isldirection::ISLDirection>(-1);

  private:
    void copy(const SendOnTag& other);

  protected:
    bool operator==(const SendOnTag&) = delete;

  public:
    SendOnTag();
    SendOnTag(const SendOnTag& other);
    virtual ~SendOnTag();
    SendOnTag& operator=(const SendOnTag& other);
    virtual SendOnTag *dup() const override {return new SendOnTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual ::core::isldirection::ISLDirection getDir() const;
    virtual void setDir(::core::isldirection::ISLDirection dir);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SendOnTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SendOnTag& obj) {obj.parsimUnpack(b);}


}  // namespace routing


namespace omnetpp {

template<> inline routing::SendOnTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<routing::SendOnTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __ROUTING_SENDONTAG_M_H

