//
// Generated file, do not edit! Created by opp_msgtool 6.3 from Global/Messages/_30_Network/SendAtTag.msg.
//

#ifndef __SATELLITE_SENDATTAG_M_H
#define __SATELLITE_SENDATTAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace satellite {

class SendAtTag;

}  // namespace satellite

#include "inet/common/TagBase_m.h" // import inet.common.TagBase


namespace satellite {

/**
 * Class generated from <tt>Global/Messages/_30_Network/SendAtTag.msg:6</tt> by opp_msgtool.
 * <pre>
 * class SendAtTag extends inet::TagBase
 * {
 *     simtime_t sendAt = inet::simTime();
 * }
 * </pre>
 */
class SendAtTag : public ::inet::TagBase
{
  protected:
    ::omnetpp::simtime_t sendAt = inet::simTime();

  private:
    void copy(const SendAtTag& other);

  protected:
    bool operator==(const SendAtTag&) = delete;

  public:
    SendAtTag();
    SendAtTag(const SendAtTag& other);
    virtual ~SendAtTag();
    SendAtTag& operator=(const SendAtTag& other);
    virtual SendAtTag *dup() const override {return new SendAtTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual ::omnetpp::simtime_t getSendAt() const;
    virtual void setSendAt(::omnetpp::simtime_t sendAt);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SendAtTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SendAtTag& obj) {obj.parsimUnpack(b);}


}  // namespace satellite


namespace omnetpp {

template<> inline satellite::SendAtTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<satellite::SendAtTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SATELLITE_SENDATTAG_M_H

