//
// Generated file, do not edit! Created by opp_msgtool 6.3 from Global/Utilities/ISLDirection.msg.
//

#ifndef __CORE__ISLDIRECTION_ISLDIRECTION_M_H
#define __CORE__ISLDIRECTION_ISLDIRECTION_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace core {
namespace isldirection {


}  // namespace isldirection
}  // namespace core


namespace core {
namespace isldirection {

/**
 * Enum generated from <tt>Global/Utilities/ISLDirection.msg:3</tt> by opp_msgtool.
 * <pre>
 * enum ISLDirection
 * {
 *     LEFT = 0;
 *     UP = 1;
 *     RIGHT = 2;
 *     DOWN = 3;
 *     GROUNDLINK = 4;
 * }
 * </pre>
 */
enum ISLDirection {
    LEFT = 0,
    UP = 1,
    RIGHT = 2,
    DOWN = 3,
    GROUNDLINK = 4
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ISLDirection& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ISLDirection& e) { int n; b->unpack(n); e = static_cast<ISLDirection>(n); }


}  // namespace isldirection
}  // namespace core


namespace omnetpp {


}  // namespace omnetpp

#endif // ifndef __CORE__ISLDIRECTION_ISLDIRECTION_M_H

