//
// Generated file, do not edit! Created by opp_msgtool 6.3 from Global/Statistics/TransmissionStatistics/CstTransmissionStatisticsTag.msg.
//

#ifndef __STATISTICS_CSTTRANSMISSIONSTATISTICSTAG_M_H
#define __STATISTICS_CSTTRANSMISSIONSTATISTICSTAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace statistics {

class CstTransmissionStatisticsTag;

}  // namespace statistics

#include "inet/common/TagBase_m.h" // import inet.common.TagBase


namespace statistics {

/**
 * Class generated from <tt>Global/Statistics/TransmissionStatistics/CstTransmissionStatisticsTag.msg:21</tt> by opp_msgtool.
 * <pre>
 * class CstTransmissionStatisticsTag extends inet::TagBase
 * {
 *     double latDev = 0;
 *     double longDev = 0;
 *     int satId = -1;
 *     double elevSat = 0;
 *     double doppler = 0;
 * 
 *     double loraTP = 0;
 *     double loraCF = 0;
 *     int loraSF = 0;
 *     double loraBW = 0;
 *     int loraCR = 0;
 * 
 *     int rcvOk = -1;
 * 
 * 
 * }
 * </pre>
 */
class CstTransmissionStatisticsTag : public ::inet::TagBase
{
  protected:
    double latDev = 0;
    double longDev = 0;
    int satId = -1;
    double elevSat = 0;
    double doppler = 0;
    double loraTP = 0;
    double loraCF = 0;
    int loraSF = 0;
    double loraBW = 0;
    int loraCR = 0;
    int rcvOk = -1;

  private:
    void copy(const CstTransmissionStatisticsTag& other);

  protected:
    bool operator==(const CstTransmissionStatisticsTag&) = delete;

  public:
    CstTransmissionStatisticsTag();
    CstTransmissionStatisticsTag(const CstTransmissionStatisticsTag& other);
    virtual ~CstTransmissionStatisticsTag();
    CstTransmissionStatisticsTag& operator=(const CstTransmissionStatisticsTag& other);
    virtual CstTransmissionStatisticsTag *dup() const override {return new CstTransmissionStatisticsTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual double getLatDev() const;
    virtual void setLatDev(double latDev);

    virtual double getLongDev() const;
    virtual void setLongDev(double longDev);

    virtual int getSatId() const;
    virtual void setSatId(int satId);

    virtual double getElevSat() const;
    virtual void setElevSat(double elevSat);

    virtual double getDoppler() const;
    virtual void setDoppler(double doppler);

    virtual double getLoraTP() const;
    virtual void setLoraTP(double loraTP);

    virtual double getLoraCF() const;
    virtual void setLoraCF(double loraCF);

    virtual int getLoraSF() const;
    virtual void setLoraSF(int loraSF);

    virtual double getLoraBW() const;
    virtual void setLoraBW(double loraBW);

    virtual int getLoraCR() const;
    virtual void setLoraCR(int loraCR);

    virtual int getRcvOk() const;
    virtual void setRcvOk(int rcvOk);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CstTransmissionStatisticsTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CstTransmissionStatisticsTag& obj) {obj.parsimUnpack(b);}


}  // namespace statistics


namespace omnetpp {

template<> inline statistics::CstTransmissionStatisticsTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<statistics::CstTransmissionStatisticsTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __STATISTICS_CSTTRANSMISSIONSTATISTICSTAG_M_H

