import torch
import torch.nn as nn

from TimePositionalEncoding import TimePositionalEncoding


class TwoBranchLoraCollisionTransformer(nn.Module):
    """
Two-branch architecture with late fusion:

      - DYNAMIC branch (Doppler, elevSat, delta_t) -> Transformer Encoder.
        These are the variables that actually change within the time
        window (relative satellite-node geometry + time), so it makes
        sense for the Transformer module to model their evolution
        using self-attention.

      - STATIC branch (latDev, longDev, loraTP, loraSF, alt, RAAN) -> MLP.
        These variables barely change within the window (they are nearly
        constant for a given node/pass), so they are processed only for
        the target packet (the last one in the window) using a dense network.
        Feeding them into the Transformer adds no value because there is no
        actual "sequence" to learn from them; it only adds parameters and noise.

      - FUSION: the representation from the dynamic branch (Transformer
        output for the target packet) is concatenated with the representation
        from the static branch (MLP output), and the resulting vector passes
        through a final dense head that produces the logit.

    The model takes as input the SAME "wide" tensor previously generated by
    `create_sequences_data` (Batch, Seq, TotalRawFeatures) and internally
    splits it into two subtensors using fixed indices (stored as buffers).
    This is crucial for exporting the model via `torch.jit.trace`/`script`
    and using it with libtorch in OMNeT++: there remains a single tensor
    input, without dictionaries or tuples of tensors.
    """

    def __init__(self,
                 d_model=32,
                 n_heads=4,
                 n_layers=2,
                 dropout=0.1,
                 static_hidden_dims=(64, 32),
                 fusion_hidden=32,
                 add_sigmoid=False):
        super().__init__()
        
        n_dynamic_features = 3 # doppler, elevSat + delta_t_norm
        n_static_features = 6 

        # ---------------- Dynamic ----------------
        self.input_projection = nn.Linear(n_dynamic_features, d_model)
        self.time_encoding = TimePositionalEncoding(d_model)
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model, nhead=n_heads,
            dim_feedforward=d_model * 4, dropout=dropout, batch_first=True,)
        
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=n_layers)

        # ---------------- Static MLP ----------------
        static_layers = []
        in_dim = n_static_features
        for h in static_hidden_dims:
            static_layers += [nn.Linear(in_dim, h), nn.ReLU(), nn.Dropout(dropout)]
            in_dim = h
        self.static_mlp = nn.Sequential(*static_layers)
        static_out_dim = static_hidden_dims[-1] if len(static_hidden_dims) > 0 else n_static_features

        # ---------------- Fusion ----------------
        head = [
            nn.Linear(d_model + static_out_dim, fusion_hidden),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(fusion_hidden, 1),
        ]
        if add_sigmoid:
            head.append(nn.Sigmoid())
        self.classifier = nn.Sequential(*head)

    def forward(self, x):
        # x: (Batch, Seq, TotalRawFeatures)
        # Layout: 0:latDev, 1:longDev, 2:elevSat, 3:loraTP, 4:loraSF, 5:doppler, 6:alt, 7:raan, 8:delta_t_norm, 9:delta_t_raw

        # X_dynamic
        delta_t_norm = x[:, :, -2].unsqueeze(-1)      # (B, S, 1) -> index 8
        delta_t_raw = x[:, :, -1]
        doppler = x[:, :, 5].unsqueeze(-1)            # (B, S, 1)
        elevSat = x[:, :, 2].unsqueeze(-1)            # (B, S, 1)
        dynamic_raw = torch.cat([doppler, elevSat], dim=-1) # (B, S, 2)
        x_dynamic = torch.cat([dynamic_raw, delta_t_norm], dim=-1)       # (B, S, 3)

        # Pass through Transformer 
        x_proj = self.input_projection(x_dynamic)
        pe = self.time_encoding(delta_t_raw)
        x_encoded = x_proj + pe
        transformer_out = self.transformer_encoder(x_encoded)
        dynamic_repr = transformer_out[:, -1, :]                         # dynamic representation 

        # X static
        static_part1 = x[:, :, :2]                    # (B, S, 2) -> latDev, longDev (index 0, 1)
        static_part2 = x[:, :, 3:5]                   # (B, S, 2) -> loraTP, loraSF (index 3, 4)
        static_part3 = x[:, :, 6:8]                   # (B, S, 2) -> alt, raan (index 6, 7)                
        x_static_full = torch.cat([static_part1, static_part2, static_part3], dim=-1) # (B, S, 6)                        
        x_static = x_static_full[:, -1, :]            # (B, 6) # We only use the last transmission 
        static_repr = self.static_mlp(x_static)

        # Fusion
        fused = torch.cat([dynamic_repr, static_repr], dim=-1)
        out = self.classifier(fused)

        return out.squeeze(-1)
