//
// Generated file, do not edit! Created by opp_msgtool 6.3 from Global/Messages/_20_Data_Link/Base_MacFrame.msg.
//

#ifndef __MAC_BASE_MACFRAME_M_H
#define __MAC_BASE_MACFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace mac {

class Base_MacFrame;

}  // namespace mac

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/linklayer/common/MacAddress_m.h" // import inet.linklayer.common.MacAddress


namespace mac {

// cplusplus {{
    using namespace inet;
// }}

/**
 * Class generated from <tt>Global/Messages/_20_Data_Link/Base_MacFrame.msg:27</tt> by opp_msgtool.
 * <pre>
 * class Base_MacFrame extends inet::FieldsChunk
 * {
 *     inet::MacAddress transmitterAddress;
 *     inet::MacAddress receiverAddress;
 * 
 *     double LoRaTP;
 *     inet::Hz LoRaCF;
 *     int LoRaSF;
 *     inet::Hz LoRaBW;
 *     int LoRaCR;
 *     bool LoRaUseHeader;
 * }
 * </pre>
 */
class Base_MacFrame : public ::inet::FieldsChunk
{
  protected:
    ::inet::MacAddress transmitterAddress;
    ::inet::MacAddress receiverAddress;
    double LoRaTP = 0;
    ::inet::Hz LoRaCF = Hz(NaN);
    int LoRaSF = 0;
    ::inet::Hz LoRaBW = Hz(NaN);
    int LoRaCR = 0;
    bool LoRaUseHeader = false;

  private:
    void copy(const Base_MacFrame& other);

  protected:
    bool operator==(const Base_MacFrame&) = delete;

  public:
    Base_MacFrame();
    Base_MacFrame(const Base_MacFrame& other);
    virtual ~Base_MacFrame();
    Base_MacFrame& operator=(const Base_MacFrame& other);
    virtual Base_MacFrame *dup() const override {return new Base_MacFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const ::inet::MacAddress& getTransmitterAddress() const;
    virtual ::inet::MacAddress& getTransmitterAddressForUpdate() { handleChange();return const_cast<::inet::MacAddress&>(const_cast<Base_MacFrame*>(this)->getTransmitterAddress());}
    virtual void setTransmitterAddress(const ::inet::MacAddress& transmitterAddress);

    virtual const ::inet::MacAddress& getReceiverAddress() const;
    virtual ::inet::MacAddress& getReceiverAddressForUpdate() { handleChange();return const_cast<::inet::MacAddress&>(const_cast<Base_MacFrame*>(this)->getReceiverAddress());}
    virtual void setReceiverAddress(const ::inet::MacAddress& receiverAddress);

    virtual double getLoRaTP() const;
    virtual void setLoRaTP(double LoRaTP);

    virtual ::inet::Hz getLoRaCF() const;
    virtual void setLoRaCF(::inet::Hz LoRaCF);

    virtual int getLoRaSF() const;
    virtual void setLoRaSF(int LoRaSF);

    virtual ::inet::Hz getLoRaBW() const;
    virtual void setLoRaBW(::inet::Hz LoRaBW);

    virtual int getLoRaCR() const;
    virtual void setLoRaCR(int LoRaCR);

    virtual bool getLoRaUseHeader() const;
    virtual void setLoRaUseHeader(bool LoRaUseHeader);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Base_MacFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Base_MacFrame& obj) {obj.parsimUnpack(b);}


}  // namespace mac


namespace omnetpp {

template<> inline mac::Base_MacFrame *fromAnyPtr(any_ptr ptr) { return check_and_cast<mac::Base_MacFrame*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MAC_BASE_MACFRAME_M_H

