//
// Generated file, do not edit! Created by opp_msgtool 6.3 from Global/Messages/_20_Data_Link/KiWanMacFrame.msg.
//

#ifndef __MAC_KIWANMACFRAME_M_H
#define __MAC_KIWANMACFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace mac {

class KiWanFrame;

}  // namespace mac

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/linklayer/common/MacAddress_m.h" // import inet.linklayer.common.MacAddress

#include "Global/Messages/_20_Data_Link/Base_MacFrame_m.h" // import Global.Messages._20_Data_Link.Base_MacFrame

// cplusplus {{
using namespace inet;
// }}


namespace mac {

/**
 * Enum generated from <tt>Global/Messages/_20_Data_Link/KiWanMacFrame.msg:15</tt> by opp_msgtool.
 * <pre>
 * // Frame type definitions 
 * enum KiWanFrameType
 * {
 *     UL_DATA = 0;      // Uplink data frame
 * }
 * </pre>
 */
enum KiWanFrameType {
    UL_DATA = 0
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const KiWanFrameType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, KiWanFrameType& e) { int n; b->unpack(n); e = static_cast<KiWanFrameType>(n); }

/**
 * Class generated from <tt>Global/Messages/_20_Data_Link/KiWanMacFrame.msg:19</tt> by opp_msgtool.
 * <pre>
 * class KiWanFrame extends Base_MacFrame
 * {
 *     int kind \@enum(KiWanFrameType);
 *     int id; // Frame identifier
 *     int srcId; // Source identifier
 *     int repetition; // Repetition count
 * 
 *     // Statistics collection
 *     double RSSI;
 *     double SNIR;
 * 
 *     // Use to compute delay
 *     double queuedAt;
 *     double sentAt;
 * }
 * </pre>
 */
class KiWanFrame : public ::mac::Base_MacFrame
{
  protected:
    int kind = 0;
    int id = 0;
    int srcId = 0;
    int repetition = 0;
    double RSSI = 0;
    double SNIR = 0;
    double queuedAt = 0;
    double sentAt = 0;

  private:
    void copy(const KiWanFrame& other);

  protected:
    bool operator==(const KiWanFrame&) = delete;

  public:
    KiWanFrame();
    KiWanFrame(const KiWanFrame& other);
    virtual ~KiWanFrame();
    KiWanFrame& operator=(const KiWanFrame& other);
    virtual KiWanFrame *dup() const override {return new KiWanFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getKind() const;
    virtual void setKind(int kind);

    virtual int getId() const;
    virtual void setId(int id);

    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);

    virtual int getRepetition() const;
    virtual void setRepetition(int repetition);

    virtual double getRSSI() const;
    virtual void setRSSI(double RSSI);

    virtual double getSNIR() const;
    virtual void setSNIR(double SNIR);

    virtual double getQueuedAt() const;
    virtual void setQueuedAt(double queuedAt);

    virtual double getSentAt() const;
    virtual void setSentAt(double sentAt);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const KiWanFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, KiWanFrame& obj) {obj.parsimUnpack(b);}


}  // namespace mac


namespace omnetpp {

template<> inline mac::KiWanFrame *fromAnyPtr(any_ptr ptr) { return check_and_cast<mac::KiWanFrame*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MAC_KIWANMACFRAME_M_H

