*.topologyControl.minimumElevation = 5.0
*.topologyControl.islDatarate = 50000000        # 50 MBit/s
*.topologyControl.groundlinkDatarate = 50000000 # 50 MBit/s

*.numSatellites = 66
*.topologyControl.walkerType = "STAR"

*.topologyControl.allowUnevenPlanes = false
# Enable ConstellationCreator to generate Walker constellation
*.constellationCreator.enabled = true
*.constellationCreator.raanSpread = 180
*.constellationCreator.inclination = 86.4
*.constellationCreator.altitude = 781
*.constellationCreator.baseYear = 20
*.constellationCreator.baseDay = ${1.5, 2.0 ! repetition}
*.constellationCreator.epochYear = 20
*.constellationCreator.epochDay = 1.5
*.**.interPlaneSpacing = 5 #5                # also required by topologycontrol
*.**.planeCount = 6                       # also required by topologycontrol

*.packetRecorder.constName = "Iridium"
